### ISSUE TITLE
Incompatible with Python 3.12

### ISSUE THREAD

**Issue by semiversus** [rob-smallshire/eseries#5]
eseries can be installed, but importing the library, the following error occurs (on python 3.12):
```
>>> import eseries
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.local/lib/python3.12/site-packages/eseries/__init__.py", line 5, in <module>
    from future import standard_library
  File "~/.local/lib/python3.12/site-packages/future/standard_library/__init__.py", line 65, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

The `imp` module has been deprecated since python 3.12. Maybe the easiest fix is to drop Python 2 support? Tell me, if I can help with a pull request.

**Comment by rob-smallshire** [comment]
A few years ago @devbisme back-ported my original Python 3 only code to Python 2. I haven't needed for Python 2 myself for over a decade. Unless folks chime in for continued support for Python 2, I'm more than happy to go back to supporting Python 3 only again.

**Comment by semiversus** [comment]
Have fixed it locally here. Will send a pull request. Basically I do the backport support only if Python < 3 is used.
